[package]
name = "webhotel"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "webhotel is a web framework."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
